- stytch/magiclink.go
- stytch/models.go
Updating `/v1/magic_links/send_by_email` to include `email_id` field in response.
> Add email_id to SendMagicByEmailResponse

- README.md
- go.mod
- stytch/magiclink/email/email.go
- stytch/magiclink/magiclink.go
- stytch/otp/otp.go
- stytch/otp/sms/sms.go
- stytch/stytch.go
- stytch/stytchapi/stytchapi.go
- stytch/stytcherror/stytcherror.go
- stytch/user/user.go
```
go get github.com/stytchauth/stytch-go@v3.0.0: github.com/stytchauth/stytch-go@v3.0.0: invalid version: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v3
```
https://stackoverflow.com/questions/53344471/taking-a-repository-to-v2
Created a protected branch for the previous major branch, v2.
> Bump go.mod Path

- stytch/attributes.go
- stytch/config/config.go
Exposes the newly-added `last_authenticated_at` timestamp on sessions authentication factors.
I tested this by sending myself a magic link and verifying that `client.MagicLinks.Authenticate` (with `SessionDurationMinutes` set) returns the right timestamp on `res.Session.AuthenticationFactors[0]`.
> feat: Add LastAuthenticatedAt field to AuthenticationFactor

- stytch/config/config.go
- stytch/session/session.go
The route for the JWKS takes the project ID as a path param instead of a query param. This fixes
the request builder for the route.
I tested by running this:
```
resp, err := client.Sessions.GetJWKS(&stytch.SessionsGetJWKSParams{ProjectID: projectID})
log.Println(err)
log.Println(resp)
```
> fix: Send JWKS project ID as a path param

- go.mod
- go.sum
- stytch/config/config.go
- stytch/session/session.go
- stytch/session/session_test.go
Some apps may find it useful to authenticate a JWT entirely locally without automatically falling
back to the `/sessions/authenticate` endpoint. This adds an `AuthenticateJWTLocal` to support
that.
This also introduces a new `ErrJWTTooOld` value for errors from the `maxTokenAge` option.
> feat: Add client.Session.AuthenticateJWTLocal

- stytch/config/config.go
- stytch/session/session.go
- stytch/session/session_test.go
In session JWTs, the session claim is the more reliable source of the session ID. The "jti" claim
happens to also contain that now, but it will not in the future.
> fix: Extract the session ID from the session claim

- stytch/config/config.go
- stytch/oauth.go
Closes https://github.com/stytchauth/stytch-go/issues/64 by adding the SessionToken and SessionJwt fields.
> Add SessionToken and SessionJwt to OAuthAuthenticate response

- stytch/config/config.go
- stytch/session.go
- stytch/session/session.go
- stytch/session/session_test.go
Stytch session JWTs now include the session's `expires_at` value within the session data claim. If
present, prefer using that value to determine the session's expiration. For backward compatibility
with old tokens that don't include it, continue using the value from the "exp" claim.
This also includes a fix for the "exp" claim's value so it's formatted like the other timestamps.
> fix: Prefer session.expires_at value in session JWT claims

- stytch/config/config.go
- stytch/stytchapi/stytchapi.go
- stytch/stytchapi/stytchapi_test.go
API client setup uses the `env` value to set the correct base URI for that environment. This is
great for the production live and test environments (which are the only supported ones!), but that
makes it difficult to use this within a Stytch development environment as a Stytch API developer.
So this adds a new `WithBaseURI` option to override the derived default.
> feat: Add WithBaseURI option to run on internal dev API

- stytch/config/config.go
- stytch/cryptowallet.go
- stytch/magiclink.go
- stytch/otp.go
- stytch/session.go
- stytch/totp.go
- stytch/user.go
- stytch/webauthn.go
We now return a user object from the following calls:
- Create User
- Update User
- Authenticate Magic Link
- Authenticate OTP
- Authenticate OAuth
- Authenticate TOTP
- Authenticate WebAuthn
- Authenticate Crypto Wallet
- Delete Email / Phone # / TOTP / WebAuth / Crypto Wallet
> feat: Add user object to update and authenticate responses

- stytch/cryptowallet.go
- stytch/magiclink.go
- stytch/otp.go
- stytch/session.go
- stytch/totp.go
- stytch/user.go
- stytch/webauthn.go
Fixes a typo introduced in #72 - this change has no effect [as noticed ](https://github.com/stytchauth/stytch-go/commit/ae16762026b76bbc35f113def62c3a925ad416a4#commitcomment-74206565) but isn't, you know, great
> fix: jspon -> json

- stytch/config/config.go
- stytch/magiclink.go
- stytch/oauth.go
Adds `code_challenge` to magic link start methods, and `code_verifier` to magic link and OAuth authenticate methods.
@stytchauth/client-libraries - any suggestion as to whether this should be a patch or a minor?
> feat: Add types for PKCE in OAuth and EML flows

- stytch/config/config.go
- stytch/stytch.go
We ran into an issue in the wild, where we hit the error on what was line 74, but were missing the original error message to know how to debug further. 
- adds a logging interface.
- add logging when they reach the error.
> Add Error Logging to Go Client 

- stytch/attributes.go
- stytch/config/config.go
- stytch/cryptowallet/cryptowallet.go
- stytch/magiclink.go
- stytch/magiclink/magiclink.go
- stytch/oauth/oauth.go
- stytch/otp/otp.go
- stytch/session/session.go
- stytch/session/session_test.go
- stytch/stytch.go
- stytch/stytchapi/stytchapi_test.go
- stytch/totp/totp.go
- stytch/webauthn/webauthn.go
Create new `AuthenticateWithClaims` functions for each product in order to authenticate that product with custom claims
Custom claims will not be visible on the session object until the product is officially released
> Add custom claims support to Go CL

- stytch/config/config.go
- stytch/cryptowallet.go
- stytch/cryptowallet/cryptowallet.go
- stytch/magiclink.go
- stytch/magiclink/magiclink.go
- stytch/oauth.go
- stytch/oauth/oauth.go
- stytch/otp.go
- stytch/otp/otp.go
- stytch/password.go
- stytch/password/email/email.go
- stytch/password/password.go
- stytch/session.go
- stytch/session/session.go
- stytch/session/session_test.go
- stytch/totp.go
- stytch/totp/totp.go
- stytch/webauthn.go
- stytch/webauthn/webauthn.go
- Add custom claims map to authenticate requests
- Add comments clarifying use of `claims interface{}` arguments in `AuthenticateWithClaims` functions
- Support custom claims for passwords
> Further custom claims support

- stytch/config/config.go
- stytch/totp.go
The TOTP create endpoint now returns a user ID and user field. This PR adds these fields to `TOTPsCreateResponse` in the Go client library.
> Add user fields to TOTP create response

- stytch/config/config.go
- stytch/user.go
- stytch/user/user.go
Delete user's biometric registration by the biometric_registration_id
> Add DeleteUserBiometricRegistration

- stytch/config/config.go
- stytch/magiclink.go
- stytch/otp.go
We have optional user_id, session_token, and session_jwt arguments for magic links email send, OTP email/sms/whatsapp send now to attach the delivery method to a user.
> BACK-1935 ML/OTP send attach method params

- stytch/config/config.go
- stytch/magiclink.go
- stytch/otp.go
- stytch/password.go
Adds support for the optional `locale` parameter for the following endpoints:
- /magic_links/email/send
- /magic_links/email/login_or_create
- /magic_links/email/invite
- /otps/email/send
- /otps/email/login_or_create
- /otps/sms/send
- /otps/sms/login_or_create
- /otps/whatsapp/send
- /otps/whatsapp/login_or_create
- /passwords/email/reset/start
The locale parameter specifies the text language of the email that the user receives. Current `locale` options are "en" (English) and "es" (Spanish).
Support for the `locale` parameter has already been added to Stytch's API endpoints.
> [SUP-11] Add locale parameter to Email Magic Links, OTP, and Passwords endpoints

- stytch/config/config.go
- stytch/oauth.go
- stytch/oauth/oauth.go
This adds support for an upcoming endpoint: OAuth Attach (`/v1/oauth/attach`).
> feat: Add support for OAuth Attach endpoint

- stytch/password.go
This adds support for `phpass` hashes in the Password Migrate endpoint
> Add PHPass password hash type

- stytch/user.go
This PR adds the missing `Password` field to the `UsersGetResponse` struct. The `User` struct has included the field since a60aae2b34dc6ac0d32973f6453b2315c74bf0c0. The `UsersGetResponse` was not changed to include it in the referenced commit.
> fix: missing Password field in UsersGetResponse

- stytch/b2c/user/user.go
- stytch/config/config.go
With the Users Search endpoint, you can get all of your pending users by adding a `Status: "pending"` filter. This can replace any and all existing calls to the Get Pending Users endpoint.
The Search method also supports more filters to further constrain results. This library also provides a SearchAll convenience helper for iterating through all the results of a search.
We'd like to remove the GetPending method from this library to limit our maintenance work and remove some complexity for customers.
This marks the GetPending method as deprecated. It will be removed in the next major version of stytch-go.
This migrates from GetPending to SearchAll, which has a cleaner iteration pattern:
**Before**
```go
ctx := context.TODO()
params := &b2c.UsersGetPendingParams{
Limit: 200,
}
res, err := …
```
> doc: Mark Users.GetPending as deprecated

- README.md
- go.mod
- go.sum
- stytch/b2c/attributes.go
- stytch/b2c/session.go
- stytch/b2c/session/session.go
- stytch/b2c/session/session_test.go
- stytch/b2c/stytchapi/stytchapi.go
- stytch/b2c/stytchapi/stytchapi_test.go
- stytch/config/config.go
This PR contains two changes related to API client startup. In order of importance:
1. Accept an init context to use when starting the API client. This allows canceling client creation if the initial JWKS fetch takes too long.
The easiest way to get this done was to upgrade through keyfunc v2.0.1 (which has a context bugfix). This is something nice to do anyway.
This option is different from our other `stytchapi.Option` arguments because it doesn't change the underlying `API` client in any way. So the init context can't easily be set as one of the variadic option args. Instead, there's a new client constructor that takes the context as the first argument.
2. Add an HTTP client override option. This is useful for anyone who needs to override the HTTP client to change things like the …
> Add client setup options for init Context and HTTP client

- README.md
- stytch/b2b/b2bstytchapi/b2bstytchapi.go
- stytch/b2c/session/session_test.go
- stytch/b2c/stytchapi/stytchapi.go
- stytch/b2c/stytchapi/stytchapi_test.go
- stytch/config/config.go
It's rare that someone would manually specify the environment unless they were working on something internally and wanted to hit internal development URLs. For every customer, they'd want the environment inferred from the given project ID (a test project can't be used in the live environment and vice versa).
This PR makes env an optional parameter and then sets it later depending on whether the project_id starts with `project-live-`.
> Add NewClient which infers environment from projectID

- .github/workflows/auto-publish.yml
- Makefile
- stytch/config/config.go
- stytch/config/version.go
Auto-publish release when version.go is updated
Moves APIVersion from `config/config.go` to `config/version.go`, but within the same package so no imports need to change.
The reason why we move `version.go` into its own file is that we detect a release by this version being updated. The only reason to ever modify `version.go` is to update the version, but `config.go` could reasonably be updated for other changes when someone *doesn't* wish to release a new version.
> Publish release whenever version.go is updated

- .github/workflows/auto-publish.yml
Action failed with a 500 error, which I'm *guessing* is due to the missing leading `v` since running `gh release create` locally succeeded.
> [auto-publish] Add leading v for version string

- stytch/config/version.go
I had run a `clean` on #127 and didn't realize the version change was overridden
> Bump version with revamp

- README.md
- stytch/b2b/b2bstytchapi/b2bstytchapi.go
- stytch/config/version.go
- stytch/consumer/stytchapi/stytchapi.go
External bug report that we weren't properly handling the underlying realClient. I believe the cause was two different PRs that went out close to one another and we just got mixed up handling the httpClient.
Created this test file locally (using real values instead of the `REDACTED` fields):
And then running it:
> Fix stytch-go NewClient with override http client

- stytch/b2b/b2bstytchapi/b2bstytchapi.go
- stytch/config/version.go
- stytch/consumer/m2m.go
- stytch/consumer/sessions.go
- stytch/consumer/stytchapi/stytchapi.go
- stytch/stytcherror/stytcherror.go
Adds a WithSkipJWKSInitialization for projects that want to override the default client but do *not* provide an easy way to initialize the JWKS client. This is somewhat common for testing purposes.
Please note that if you skip JWKS initialization and then call an API method that uses JWKS, it **will** try to dereference a `nil` pointer.
Used a simple test.go script that skipped JWKS and sent an EML
> Add option to skip JWKS initialization

- stytch/b2b/organizations.go
- stytch/b2b/organizations/members/types.go
- stytch/b2b/organizations/types.go
- stytch/b2b/organizations_members.go
- stytch/b2b/otp_sms.go
- stytch/b2b/passwords/session/types.go
- stytch/b2b/sessions.go
- stytch/b2b/sso/saml/types.go
- stytch/b2b/sso/types.go
- stytch/b2b/sso_saml.go
- stytch/config/version.go
- stytch/consumer/otp_sms.go
- stytch/consumer/sessions.go
- stytch/consumer/totps/types.go
- stytch/consumer/users/types.go
- stytch/consumer/webauthn.go
- stytch/consumer/webauthn/types.go
Add "dangerously get member" to SDKs
SAML Update by URL and Doc
> Add "dangerously get member" to SDKs and SAML Update by URL and Doc

- stytch/b2b/discovery/organizations/types.go
- stytch/b2b/organizations/members/types.go
- stytch/b2b/organizations/types.go
- stytch/b2b/rbac.go
- stytch/b2b/rbac/types.go
- stytch/config/version.go
- stytch/consumer/passwords/types.go
1. Docs updates
2. Adds support for `set_email_verified` in passwords/migrate
> Update docs and support set_email_verified

- stytch/b2b/sessions.go
- stytch/b2b/sessions_test.go
- stytch/config/version.go
- stytch/consumer/sessions.go
- stytch/consumer/sessions_test.go
- stytch/shared/jwt.go
- stytch/shared/jwt_test.go
This fixes a bug that causes custom claims to be omitted from the returned Session value when authenticating a Session JWT locally. This affects `AuthenticateJWTLocal` directly. The change also applies to `AuthenticateJWT` and `AuthenticateJWTWithClaims` which prefer using it for local validation over sending a request to the API.
The fix is to separate the app's custom claims from the standard and Stytch-specific JWT claims. This is complicated slightly by the fact that the Stytch session claim is a large, complex struct and custom claims are effectively unconstrained.
I see two options:
1. Parse the claims into `jwt.MapClaims` and split the claims by key into known and unknown sets.
2. Parse the claims twice: once into `sessions.SessionClaim` and once into `jwt.MapClaims` (and then …
> fix: Return custom claims when authenticating a JWT locally

- stytch/b2b/organizations/members/oauthproviders/types.go
- stytch/b2b/organizations_members_oauthproviders.go
- stytch/config/version.go
This is a major version bump because we have a breaking change: we need to rename `MicrosoftParams` to `ProviderInformationParams`, since it's used for more than just Microsoft OAuth.
> Change MicrosoftParams to ProviderInformationParams

- stytch/b2b/organizations/members/types.go
- stytch/config/version.go
This has to be a MAJOR update since we're breaking an API, but otherwise this is a really straightforward change. We've also added support in the codegen backend to support this more easily in the future.
> Fixes #177 - use pointer to roles for Member.Update

- stytch/config/version.go
- stytch/consumer/m2m.go
- stytch/consumer/m2m/types.go
- stytch/consumer/m2m_test.go
- stytch/shared/m2m_authorization.go
- stytch/shared/m2m_authorization_test.go
- stytch/stytcherror/stytcherror.go
This PR adds support for wildcard scopes in M2M auth.
This means that an M2M client can have a scope like `read:*` and if given a required scope of `read:foo`, authentication will be allowed.
This does *not* affect "simple" scopes like `read` or `read_users` -- only scopes with a separating `:` are supported.
Furthermore, the assumption is that the scopes will be given as `action:resource`, though it is technically possible to assign in a different way like `users:read`, though in that case, a scope of `users:*` would **not** match a required scope of `read:users`. But as long as an application is consistent, this would be allowed.
Furthermore, a scope of just `*` does **not** get interpreted as an "omniscient" client -- instead, this is seen as the literal character `*` and gets matched …
> Support wildcard scopes in M2M auth

- README.md
Updates our readme to be more in-line with the Java SDK's and include B2B Examples!
> Update readme to include B2B Examples

- DEVELOPMENT.md
- README.md
Update Slack Invite links to point to the Support landing page as a single source of truth (Slack invite links expire after 400 uses and need to be updated semi frequently).
> Update slack links

- stytch/b2b/organizations/types.go
- stytch/b2b/scim/connection/types.go
- stytch/b2b/scim/types.go
- stytch/b2b/scim_connection.go
- stytch/config/version.go
- stytch/consumer/cryptowallets/types.go
Changes the SIWE `ChainID` type to a `string` rather than `uint32`. Since SIWE isn't released yet, I'm marking this as a minor version bump.
> Change ChainID to string

- stytch/config/version.go
- stytch/consumer/fraud/rules/types.go
- stytch/consumer/fraud/types.go
- stytch/consumer/fraud_rules.go
This PR adds support for IPGEO in the fraud rules endpoint. You can now set rules on CIDR blocks, ASNs, and country codes. The fingerprint lookup endpoint will now also return information on which rule type and identifier were applied, if a `RULE_MATCH` reason was returned.
> Add IPGEO to DFP rules endpoint

- .golangci.yml
This was causing issues with auto-generated libraries.
> Remove `lll` from lint config

- stytch/consumer/m2m_test.go
- stytch/shared/rbac_local_test.go
- stytch/stytcherror/stytcherror.go
Error details are used on stytcherrors to provide more info. I added error details to the invalid_email_for_jit_provisioning error in the API code, and piped them through to replay errors, but they still need to be added in the SDK code. This adds it for the GO code.
Testing:
I created a simple go app that hit my local version of the SDK and confirmed when I use an invalid email I see the error details now:
> Pipe error details through to stytch-go SDK

- stytch/b2b/b2bstytchapi/b2bstytchapi.go
- stytch/b2b/sessions.go
- stytch/b2b/sessions_test.go
- stytch/config/version.go
- stytch/consumer/m2m.go
- stytch/consumer/m2m_test.go
- stytch/consumer/sessions.go
- stytch/consumer/sessions_test.go
- stytch/consumer/stytchapi/stytchapi.go
- stytch/shared/jwt.go
We are in the process of changing the issuer that JWTs return to be the base URL of the request we received on `authenticate` (this is in line with the OIDC spec). We want to accept that issuer as well as the default one in our JWT local auth methods.
> Updates Issuer Validation to Fallback to BaseURI

- stytch/stytcherror/stytcherror.go
Previously I had added Details to the Error object so that error details from the API would be piped through. However I added it as map[string]string which fails if it's a nested object. This changes it to map[string]any so it accounts for this.
> Small update the type of error details to allow for nested objects

- stytch/b2b/b2bstytchapi/b2bstytchapi.go
- stytch/b2b/idp.go
- stytch/b2b/idp/types.go
- stytch/config/version.go
- stytch/shared/rbac_local.go
This PR adds the `IntrospectTokenLocal` function under a new IDP client. This function can be used to introspect access tokens minted by our connected apps flow.
> Add IntrospectTokenLocal function for connected apps

- stytch/consumer/idp.go
- stytch/consumer/idp/types.go
- stytch/consumer/idp_test.go
Part of AUTH-5632 and essentially a port of #250 to Consumer
This PR does _not_ handle Consumer `AuthorizationCheck` logic. Will add in a future PR.
> feat: [AUTH-5632] Add Consumer IntrospectToken methods

- stytch/b2b/idp.go
- stytch/b2b/sessions.go
- stytch/consumer/sessions.go
- stytch/consumer/sessions/types.go
- stytch/consumer/sessions_test.go
- stytch/consumer/stytchapi/stytchapi.go
- stytch/shared/rbac_local.go
- stytch/shared/rbac_local_helpers.go
- stytch/shared/rbac_local_test.go
This PR:
- Partially runs codegen to get Consumer Authorization structs 
- Adds internal methods for converting Consumer RBAC and B2B RBAC policies into a shared format
- Refactors the existing B2B RBAC methods to use shared format
- Implements Consumer RBAC internal methods and tests
Next PR:
- Will start to use internal Consumer RBAC methods in Consumer public client endpoints
> feat: [AUTH-5632] Refactor internals for Consumer RBAC Authorization
