.github/workflows/build.yml, README.md, stytch/magiclink.go, stytch/models.go
Adds the new LoginOrInvite & LoginOrCreate endpoints
- [API-90](https://linear.app/stytch/issue/API-90)
Please describe the tests that you ran to verify your changes.
Manual test:
- Tested both endpoints with my local go project
=> API-90: Add LoginOrInvite & LoginOrCreate

stytch/email.go, stytch/models.go
Removes the stand alone email verify endpoints
=> Remove Email Verify Endpoints 

README.md, stytch/client.go, stytch/error.go, stytch/magiclink.go, stytch/models.go, stytch/user.go
Adds support for the new invite related methods
=> Add Invite By Email, Revoke Invite & Get Invited Users

stytch/client.go, stytch/error.go, stytch/models.go
Adds status code to responses & refactors status in errors to be status_code
=> Add Status Code to Responses

stytch/client.go
=> Add User-Agent to Request

stytch/config/config.go, stytch/user.go
Tested using https://github.com/stytchauth/stytch-go-magic-links
=> Authenticator type for webauthn registrations

stytch/config/config.go, stytch/cryptowallet.go, stytch/magiclink.go, stytch/otp.go, stytch/session.go, stytch/totp.go, stytch/webauthn.go
Add session_jwt to all authenticate requests and responses
=> Add session_jwt to all authenticate requests and responses

stytch/attributes.go
=> Add biometric session factors

stytch/config/config.go, stytch/cryptowallet.go
Attach to existing user via user_id already exists, add session params as well
=> Cryptowallet attach via session params

stytch/config/config.go
=> fix: Bump major version

stytch/config/config.go, stytch/magiclink.go, stytch/otp.go, stytch/password.go
=> feat: Add template ID parameters

stytch/config/config.go, stytch/password.go
Adding the new password strength response fields for the passwords configurability project. Current protos [here](https://github.com/stytchauth/protobuf/blob/0d242bb6a7ae63f91a12fe8049a8e748977e2c0b/api/password/v1/password.proto#L172-L195)
=> New PasswordStrengthCheckResponse fields

stytch/config/config.go, stytch/session.go
As mentioned in https://stytch.slack.com/archives/C015UDB4X33/p1678730527302449
=> austin/sessions: add session_jwt to SessionsRevokeParams

stytch/b2b/password.go, stytch/b2b/password/password.go, stytch/config/config.go
- Add Member Password Delete
- add OrgID to PasswordsAuthenticate
=> chore: fix a few misses from b2b initial release

stytch/b2b/b2bstytchapi/b2bstytchapi.go, stytch/config/version.go
=> Use B2B Sessions JWKS URL

stytch/b2b/sessions/types.go, stytch/config/version.go, stytch/consumer/magiclinks_email.go, stytch/consumer/otp_email.go, stytch/consumer/otp_sms.go, stytch/consumer/otp_whatsapp.go, stytch/consumer/passwords/session/types.go, stytch/consumer/sessions/types.go, stytch/consumer/users.go
Adds additional params to the PasswordsSessionReset method and reruns autogen.
=> feat: [AUTH-1645] Add additional params to PasswordsSessionReset

stytch/shared/rbac_local.go, stytch/shared/rbac_local_test.go, stytch/stytcherror/stytcherror.go
Define specific errors for local authorization
=> Make authorization errors more specific

stytch/stytcherror/stytcherror.go
Consistent with Ruby/other languages now
Original PR: https://github.com/stytchauth/stytch-go/pull/159
=> Update Authz Error Messaging

stytch/b2b/organizations/members/types.go, stytch/b2b/passwords/types.go, stytch/config/version.go
`preserve_existing_sessions` should be an optional argument
=> Mark preserve_existing_sessions optional

DEVELOPMENT.md, README.md
Context: https://stytchio.slack.com/archives/C03VCND8D7Z/p1710859226666469
- [LINEAR-NUMBER](https://linear.app/stytch/issue/YOUR-TICKET)
- List any dependencies that are required for this change.
Please describe the tests that you ran to verify your changes.
=> Update slack URLs

stytch/b2b/discovery/intermediatesessions/types.go, stytch/b2b/discovery/organizations/types.go, stytch/b2b/magiclinks/discovery/types.go, stytch/b2b/magiclinks/types.go, stytch/b2b/oauth/discovery/types.go, stytch/b2b/oauth/types.go, stytch/b2b/organizations/members/oauthproviders/types.go, stytch/b2b/organizations/members/types.go, stytch/b2b/otp/sms/types.go, stytch/b2b/passwords/email/types.go, stytch/b2b/passwords/existingpassword/types.go, stytch/b2b/passwords/session/types.go, stytch/b2b/passwords/types.go, stytch/b2b/recoverycodes/types.go, stytch/b2b/sessions/types.go, stytch/b2b/sso/types.go, stytch/b2b/totps/types.go, stytch/config/version.go, stytch/consumer/oauth/types.go, stytch/consumer/sessions/types.go
I marked this as a patch change because the only additions in this PR are docs.
=> Add B2B step-up docs

stytch/b2b/organizations/types.go, stytch/b2b/organizations_members.go, stytch/b2b/scim/connection/types.go, stytch/b2b/scim/types.go, stytch/config/version.go, stytch/consumer/cryptowallets.go, stytch/consumer/cryptowallets/types.go, stytch/consumer/sessions.go, stytch/consumer/sessions/types.go
Adds Sign in With Ethereum (SIWE) to the crypto wallets endpoints. Also updates docs for some other products.
=> Add Sign in With Ethereum

stytch/b2b/scim/types.go, stytch/config/version.go
Adds in some missing properties for SCIM Attributes.
=> Add in additional SCIM Attributes to get parity to spec
